- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'mysql', state: 'absent'} #item-1
    - { name: 'nginx', state: 'latest'} #item-2
    - { name: 'postfix', state: 'absent'} #item-3
