- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'Hi this is from command module' > /tmp/command.txt "
  
  - name: shell module
    ansible.builtin.shell: "echo 'Hi this is from shell module' > /tmp/shell.txt "

# simple commands without the need of shell variables, environment and features like redirections, pipes, & then go for command module.
# if we need to run complex commands or scripts then go for shell module
# whatever works in command module will works in shell module but vice versa is not true.